### ISSUE TITLE
missing 1 required positional argument: 'resend'

### ISSUE THREAD

**Issue by zhoulian1992** [zhuyu4839/zlgcan-driver#2]
I copied the code in readme file, there was an error when I run. The error as following:

Traceback (most recent call last):
  File "D:/zhoulian_files/CANTest/main.py", line 6, in <module>
    with can.Bus(bustype='zlgcan', device_type=ZCANDeviceType.ZCAN_USBCANFD_200U, resend=True,
  File "C:\Users\m\.virtualenvs\CANTest-FkfklYjI\lib\site-packages\can\interface.py", line 125, in __new__
    bus = cls(*args, **kwargs)
  File "C:\Users\m\.virtualenvs\CANTest-FkfklYjI\lib\site-packages\can\interfaces\zlgcan.py", line 238, in __init__
    self.device = ZCAN()
TypeError: __init__() missing 1 required positional argument: 'resend'

**Comment by jesses2025smith** [comment]
已修复python-can interface的resend参数报错的bug
