### ISSUE TITLE
ValueError: ZLGCAN - Method: ZCAN_OpenDevice execute failed, code: 0!

### ISSUE THREAD

**Issue by Happiness-yuan** [zhuyu4839/zlgcan-driver#8]
您好，我按照流程安装完所有的库之后，打不开我的设备。能分享一下，该如何去排查问题在哪吗？
下面是我安装的库：
```
Package           Version
----------------- -------
chardet           5.2.0
construct         2.10.70
Mako              1.3.5
MarkupSafe        2.1.5
packaging         24.1
pip               24.0
pybind11          2.13.1
pyserial          3.5
python-can        4.4.2
pyusb             1.2.1
pywin32           306
pyxcp             0.21.11
setuptools        69.5.1
setuptools-cpp    0.1.0
toml              0.10.2
traitlets         5.14.3
typing_extensions 4.12.2
uptime            3.0.1
wheel             0.43.0
wrapt             1.16.0
zlgcan-driver-py  0.1.4
```
程序运行报错：
```
Traceback (most recent call last):
  File "D:\WorkSpace\VSCode\myCANTool\myCANTool_ZLGCAN\main.py", line 4, in <module>
    with can.Bus(interface="zlgcan", device_type=ZCANDeviceType.ZCAN_USBCAN2,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\mypycan\Lib\site-packages\can\util.py", line 379, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\mypycan\Lib\site-packages\can\interface.py", line 133, in Bus
    bus = cls(**kwargs)
          ^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\mypycan\Lib\site-packages\can\interfaces\zlgcan\zlgcan.py", line 184, in __init__
    raise e
  File "D:\software\anaconda3\envs\mypycan\Lib\site-packages\can\interfaces\zlgcan\zlgcan.py", line 156, in __init__
    self.device = zlgcan_open(device_type, device_index, derive)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: ZLGCAN - Method: ZCAN_OpenDevice execute failed, code: 0!
```

**Comment by jesses2025smith** [comment]
USBCAN2？
[排查有没有安装周立工的[C++环境](http://manual.zlg.cn/server/index.php?s=/api/attachment/visitFile/sign/5e5f2a5e6a0ee80db6af38a6e9e224f0)，如果需要时效性的解决+Wx: oscillo_scope(免费远程协助)
